In [8]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.5.2

In [13]:
df = pd.read_csv("../data/raw/PakWheels Dataset.csv")
df.head()

,nam,Price,Year,Millage,Fuel,Transmission,Province,Color,Assembly,Engine Capacity,Body Type,Ad Reference,Features,Owner nam,url
0,Suzuki Alto VXL AGS 2022,PKR 23.9 lacs,2022,"120,000 km",Petrol,Automatic,Islamabad,Solid White,Local,660 cc,Hatchback,10313920,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Daniyal,https://www.pakwheels.com//used-cars/suzuki-al...
1,Honda N Box Custom GL 2022,PKR 33.4 lacs,2022,"37,110 km",Petrol,Automatic,Islamabad,White,Imported,658 cc,Hatchback,10233745,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/honda-n-b...
2,Honda Civic EX 1995,PKR 6.3 lacs,1995,786 km,LPG,Manual,Karachi,Black,Local,1500 cc,Sedan,10313884,"['AM/FM Radio', 'Air Conditioning', 'Cassette ...",Abdullah Sheikh,https://www.pakwheels.com//used-cars/honda-civ...
3,Toyota Corolla GLi Automatic 1.6 VVTi 2012,PKR 33.25 lacs,2012,"133,000 km",Petrol,Automatic,Lahore,Medium Silver,Imported,1600 cc,Sedan,10311918,"['ABS', 'AM/FM Radio', 'Air Conditioning', 'CD...",Zakiulhassan,https://www.pakwheels.com//used-cars/toyota-co...
4,Toyota Corolla Hatchback 1998,PKR 16.45 lacs,1998,"125,225 km",Petrol,Automatic,Punjab,Black,Local,1600 cc,NaN,10207521,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/toyota-co...

In [14]:
df.shape

(61919, 15)

In [15]:
df.columns.tolist()

['nam',
 'Price',
 'Year',
 'Millage',
 'Fuel',
 'Transmission',
 'Province',
 'Color',
 'Assembly',
 'Engine Capacity',
 'Body Type',
 'Ad Reference',
 'Features',
 'Owner nam',
 'url']

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61919 entries, 0 to 61918
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nam              61919 non-null  str
 1   Price            61919 non-null  str
 2   Year             61919 non-null  int64
 3   Millage          61919 non-null  str
 4   Fuel             61919 non-null  str
 5   Transmission     61919 non-null  str
 6   Province         61919 non-null  str
 7   Color            61918 non-null  str
 8   Assembly         61919 non-null  str
 9   Engine Capacity  61919 non-null  str
 10  Body Type        54732 non-null  str
 11  Ad Reference     61919 non-null  int64
 12  Features         58042 non-null  str
 13  Owner nam        53493 non-null  str
 14  url              61919 non-null  str
dtypes: int64(2), str(13)
memory usage: 7.1 MB

In [17]:
df.isnull().sum().sort_values(ascending=False)

Owner nam          8426
Body Type          7187
Features           3877
Color                 1
nam                   0
Price                 0
Year                  0
Province              0
Transmission          0
Fuel                  0
Millage               0
Engine Capacity       0
Assembly              0
Ad Reference          0
url                   0
dtype: int64

In [18]:
(df.isnull().mean() * 100).sort_values(ascending=False)

Owner nam          13.608101
Body Type          11.607100
Features            6.261406
Color               0.001615
nam                 0.000000
Price               0.000000
Year                0.000000
Province            0.000000
Transmission        0.000000
Fuel                0.000000
Millage             0.000000
Engine Capacity     0.000000
Assembly            0.000000
Ad Reference        0.000000
url                 0.000000
dtype: float64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.nunique().sort_values()

Transmission           2
Assembly               2
Fuel                   6
Body Type             21
Year                  68
Province             123
Engine Capacity      251
Color                983
Price               2204
Features            5077
nam                 8809
Millage             9011
Owner nam          27326
Ad Reference       61911
url                61911
dtype: int64

In [21]:
df["Price"].head(20)

0      PKR 23.9 lacs
1      PKR 33.4 lacs
2       PKR 6.3 lacs
3     PKR 33.25 lacs
4     PKR 16.45 lacs
5     PKR 23.49 lacs
6      PKR 3.5 crore
7      PKR 68.5 lacs
8     PKR 3.45 crore
9     PKR 10.95 lacs
10    PKR 69.85 lacs
11     PKR 21.4 lacs
12     PKR 17.8 lacs
13     PKR 28.5 lacs
14       PKR 79 lacs
15     PKR 64.5 lacs
16     PKR 17.2 lacs
17     PKR 1.3 crore
18     PKR 35.5 lacs
19      PKR 8.1 lacs
Name: Price, dtype: str

In [22]:
df["Price"].value_counts().head(20)

Price
Call for price    853
PKR 25 lacs       560
PKR 23.5 lacs     519
PKR 22.5 lacs     490
PKR 35 lacs       485
PKR 24.5 lacs     483
PKR 12.5 lacs     481
PKR 26.5 lacs     475
PKR 23 lacs       471
PKR 24 lacs       466
PKR 32 lacs       464
PKR 8.5 lacs      461
PKR 10.5 lacs     451
PKR 26 lacs       441
PKR 12 lacs       440
PKR 9.5 lacs      437
PKR 22 lacs       427
PKR 30 lacs       413
PKR 11.5 lacs     413
PKR 11 lacs       398
Name: count, dtype: int64

In [23]:
df["Price"].tail(20)

61899      PKR 8.5 lacs
61900       PKR 52 lacs
61901       PKR 35 lacs
61902       PKR 17 lacs
61903       PKR 31 lacs
61904     PKR 9.05 lacs
61905      PKR 6.8 lacs
61906       PKR 46 lacs
61907     PKR 11.8 lacs
61908    PKR 16.65 lacs
61909       PKR 11 lacs
61910       PKR 11 lacs
61911     PKR 36.5 lacs
61912     PKR 31.5 lacs
61913       PKR 26 lacs
61914    PKR 15.95 lacs
61915       PKR 37 lacs
61916       PKR 20 lacs
61917       PKR 70 lacs
61918      PKR 4.9 lacs
Name: Price, dtype: str

In [24]:
df["Millage"].head(20)

0     120,000 km
1      37,110 km
2         786 km
3     133,000 km
4     125,225 km
5       4,100 km
6       4,917 km
7      75,000 km
8      22,000 km
9     180,000 km
10     43,736 km
11    170,000 km
12          1 km
13    147,500 km
14     28,874 km
15     31,500 km
16     60,000 km
17      3,497 km
18    113,026 km
19    100,000 km
Name: Millage, dtype: str

In [25]:
df["Millage"].value_counts().head(20)

Millage
100,000 km    3219
150,000 km    1779
200,000 km    1501
80,000 km     1157
90,000 km      851
120,000 km     849
50,000 km      833
70,000 km      805
60,000 km      677
10,000 km      662
85,000 km      600
140,000 km     533
130,000 km     523
75,000 km      520
95,000 km      501
65,000 km      499
110,000 km     498
40,000 km      493
160,000 km     488
1 km           479
Name: count, dtype: int64

In [26]:
df["Engine Capacity"].head(20)

0       660 cc
1       658 cc
2      1500 cc
3      1600 cc
4      1600 cc
5       800 cc
6      2700 cc
7      1500 cc
8     71.0 kWh
9      1000 cc
10     2000 cc
11     1500 cc
12     1600 cc
13     1500 cc
14     1600 cc
15     1500 cc
16      800 cc
17     3000 cc
18     1600 cc
19     1300 cc
Name: Engine Capacity, dtype: str

In [27]:
df["Engine Capacity"].value_counts().head(20)

Engine Capacity
1000 cc    11554
1300 cc     9682
660 cc      8905
1500 cc     6938
800 cc      5721
1800 cc     5470
1600 cc     2812
2000 cc     1896
796 cc      1379
1200 cc      969
2700 cc      885
2800 cc      713
3000 cc      701
2500 cc      604
2400 cc      332
3500 cc      323
4600 cc      317
1400 cc      215
1598 cc      175
4200 cc      151
Name: count, dtype: int64

In [28]:
df["Fuel"].value_counts(dropna=False)

Fuel
Petrol      53431
Hybrid       4875
Diesel       2258
CNG           651
Electric      550
LPG           154
Name: count, dtype: int64

In [29]:
df["Transmission"].value_counts(dropna=False)

Transmission
Automatic    34537
Manual       27382
Name: count, dtype: int64

In [30]:
df["Assembly"].value_counts(dropna=False)

Assembly
Local       39090
Imported    22829
Name: count, dtype: int64

In [31]:
df["Body Type"].value_counts(dropna=False)

Body Type
Hatchback            22785
Sedan                19521
NaN                   7187
SUV                   3716
Crossover             3640
Mini Van              1053
Van                    579
Micro Van              526
Double Cabin           476
Pick Up                467
Compact sedan          447
MPV                    431
Compact SUV            408
Station Wagon          208
Mini Vehicles          168
Coupe                   98
Truck                   93
Convertible             49
High Roof               24
Single Cabin            24
Off-Road Vehicles       18
Compact hatchback        1
Name: count, dtype: int64

In [32]:
df["Province"].value_counts().head(30)

Province
Islamabad           13453
Lahore              12869
Punjab               9258
Sindh                8449
Karachi              7953
Un-Registered        5687
Rawalpindi            786
Multan                607
Peshawar              535
Faisalabad            518
Abbottabad            300
Adda jahan khan       214
Sialkot               191
Gujranwala            124
Bahawalpur             96
Hyderabad              71
Quetta                 66
Rahim Yar Khan         63
Sargodha               59
Mirpur A.K.            44
Gujrat                 39
Sahiwal                39
Swat                   34
Mardan                 30
Okara                  25
Jhelum                 23
Sheikhupura            16
Muzaffarabad           16
Dera ismail khan       15
Bahawalnagar           15
Name: count, dtype: int64

In [33]:
df["Province"].head(20)

0         Islamabad
1         Islamabad
2           Karachi
3            Lahore
4            Punjab
5         Islamabad
6     Un-Registered
7         Islamabad
8         Islamabad
9           Karachi
10           Punjab
11        Islamabad
12           Lahore
13       Rawalpindi
14           Punjab
15           Punjab
16           Punjab
17          Karachi
18            Sindh
19           Lahore
Name: Province, dtype: str

In [34]:
df["Color"].value_counts(dropna=False).head(30)

Color
White                        14676
Silver                        5787
Black                         5476
Solid White                   3746
Grey                          3217
Blue                          2115
Taffeta White                 1567
Super White                   1537
Graphite Grey                 1359
Green                         1048
Red                            989
Attitude Black                 973
Silky Silver                   953
Silver Metallic                926
Gold                           885
Snow White Pearl               825
Maroon                         768
Pearl White                    607
Beige                          589
Crystal Black                  529
Burgundy                       492
Lunar Silver Metallic          449
Polar White                    398
Crystal Black Pearl            381
Turquoise                      330
Brown                          298
White Pearl Crystal Shine      288
Modern Steel Metallic          258
Alabaster Silver               258
Bronze                         238
Name: count, dtype: int64

In [35]:
df["Color"].head(30)

0                        Solid White
1                              White
2                              Black
3                      Medium Silver
4                              Black
5                        Solid White
6          White Pearl Crystal Shine
7                              White
8     Sophisto Grey Brilliant Effect
9                               Blue
10                             White
11                             Black
12                             White
13                            Bronze
14                      Quartz Black
15                             White
16                       Solid White
17                             Black
18                     Phantom Brown
19                         Keen Gold
20           Dark Grey Mica Metallic
21                             White
22                              Navy
23             Lunar Silver Metallic
24                      Silky Silver
25             Lunar Silver Metallic
26                       Solid White
27                               Red
28             Lunar Silver Metallic
29                          Wine Red
Name: Color, dtype: str

In [36]:
df["nam"].head(30)

0                         Suzuki Alto VXL AGS 2022
1                       Honda N Box Custom GL 2022
2                              Honda Civic EX 1995
3       Toyota Corolla GLi Automatic 1.6 VVTi 2012
4                    Toyota Corolla Hatchback 1998
5              Suzuki Bolan Cargo Van Euro ll 2024
6               Toyota Prado TX L Package 2.7 2022
7            Honda Civic 1.5 VTEC Turbo Oriel 2021
8                             BMW iX xDrive40 2022
9                             Suzuki Alto VXR 2006
10                           KIA Sportage AWD 2021
11                 Honda City VTEC Steermatic 2006
12             Suzuki Liana Eminent Automatic 2010
13               Honda City Aspire 1.5 i-VTEC 2014
14             Chery Tiggo 8 Pro 1.6 DEX Plus 2023
15                               MG HS Trophy 2021
16                    Suzuki Bolan VX Euro II 2022
17    Isuzu D-Max V-Cross Limited GTX Edition 2024
18         Toyota Corolla Altis Automatic 1.6 2015
19                              Suzuki Baleno 1999
20               Toyota Prado RZ 3.4 (3-Door) 2003
21                           KIA Sportage FWD 2024
22                         Toyota C-HR G Nero 2019
23           Honda Civic Oriel 1.8 i-VTEC CVT 2018
24                         Suzuki Wagon R VXL 2018
25               Honda City Aspire 1.5 i-VTEC 2018
26                        Suzuki Ravi Euro II 2018
27             Honda Civic Turbo 1.5 VTEC CVT 2016
28                      Honda City 1.3 i-VTEC 2016
29                Toyota Corolla GLi 1.3 VVTi 2012
Name: nam, dtype: str

In [37]:
df["nam"].value_counts().head(30)

nam
Toyota Raize Z 2020                      466
Suzuki Alto VXR 2022                     337
Honda Civic Oriel 1.8 i-VTEC CVT 2017    299
Honda Civic Oriel 1.8 i-VTEC CVT 2018    294
Suzuki Mehran VXR Euro II 2018           294
Suzuki Mehran VXR Euro II 2017           275
Suzuki Alto VXR 2021                     261
Honda Civic Oriel 1.8 i-VTEC CVT 2021    204
Suzuki Cultus VXR 2006                   199
Suzuki Mehran VXR Euro II 2016           194
Suzuki Alto VXR 2024                     193
Suzuki Cultus VXR 2007                   186
Suzuki Wagon R VXL 2018                  184
Suzuki Mehran VXR Euro II 2015           180
Toyota Corolla GLi 1.3 VVTi 2011         178
Honda Civic Oriel 1.8 i-VTEC CVT 2019    176
Suzuki Cultus VXRi 2008                  175
Toyota Corolla GLi 1.3 VVTi 2010         175
Suzuki Alto VXL AGS 2022                 167
Suzuki Cultus Limited Edition 2016       154
Honda City 1.3 i-VTEC 2018               149
Toyota Corolla GLi 1.3 VVTi 2012         148
Suzuki Wagon R VXL 2017                  148
Toyota Corolla GLi 1.3 VVTi 2016         148
Toyota Corolla GLi 1.3 VVTi 2015         146
Honda Civic Oriel 1.8 i-VTEC CVT 2020    146
Suzuki Alto VXL AGS 2021                 143
Honda City 1.3 i-VTEC 2016               141
Honda City i-DSI 2006                    139
Toyota Corolla XLi VVTi 2010             139
Name: count, dtype: int64

In [38]:
df["Year"].describe()

count    61919.000000
mean      2012.798026
std          9.000544
min       1900.000000
25%       2007.000000
50%       2015.000000
75%       2020.000000
max       2025.000000
Name: Year, dtype: float64

In [39]:
df["Year"].value_counts().sort_index()

Year
1900       2
1952       2
1956       2
1960       2
1961       1
        ...
2021    4881
2022    4395
2023    1644
2024    1363
2025    1702
Name: count, Length: 68, dtype: int64

In [40]:
df[df["Year"] == 1900]

,nam,Price,Year,Millage,Fuel,Transmission,Province,Color,Assembly,Engine Capacity,Body Type,Ad Reference,Features,Owner nam,url
11957,Hyundai Santro 1900,PKR 11.75 lacs,1900,"15,000 km",Petrol,Manual,Punjab,White,Local,1300 cc,NaN,10306396,NaN,Danish,https://www.pakwheels.com//used-cars/hyundai-s...
20469,Suzuki Ravi 1900,PKR 4 lacs,1900,"88,000 km",Petrol,Manual,Karachi,White,Imported,800 cc,NaN,10297870,NaN,Shakeel,https://www.pakwheels.com//used-cars/suzuki-ra...

In [41]:
name_year = pd.to_numeric(
    df["nam"].str.extract(r'(\d{4})$')[0],
    errors="coerce"
)

(name_year != df["Year"]).sum()

np.int64(0)

In [42]:
name_year.isna().sum()

np.int64(0)

In [43]:
df["Features"].head(20)

0     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
1     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
2     ['AM/FM Radio', 'Air Conditioning', 'Cassette ...
3     ['ABS', 'AM/FM Radio', 'Air Conditioning', 'CD...
4     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
5     ['AM/FM Radio', 'CD Player', 'DVD Player', 'Im...
6     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
7     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
8     ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
9     ['AM/FM Radio', 'Air Conditioning', 'CD Player...
10    ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
11    ['AM/FM Radio', 'Air Conditioning', 'Alloy Rim...
12    ['ABS', 'AM/FM Radio', 'Air Conditioning', 'Al...
13    ['ABS', 'AM/FM Radio', 'Air Conditioning', 'Al...
14    ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
15    ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
16    ['AM/FM Radio', 'Front Speakers', 'Immobilizer...
17    ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
18    ['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...
19                                       ['Alloy Rims']
Name: Features, dtype: str

In [44]:
import ast

feature_lists = df["Features"].dropna().apply(ast.literal_eval)

all_features = feature_lists.explode()

all_features.value_counts()

Features
AM/FM Radio                53686
Air Conditioning           53569
Power Steering             47580
Power Locks                46736
Power Windows              43214
Immobilizer Key            41698
Power Mirrors              40066
Keyless Entry              37947
ABS                        37779
Air Bags                   34512
Alloy Rims                 31027
CD Player                  28276
Navigation System          16419
DVD Player                 15902
Cruise Control             15337
Front Speakers              9866
Sun Roof                    9034
USB and Auxillary Cable     8101
Cassette Player             7032
Rear Speakers               4741
CoolBox                     3320
Rear Camera                 3220
Climate Control             3054
Steering Switches           2956
Rear AC Vents               1409
Front Camera                 863
Heated Seats                 854
Rear Seat Entertainment      182
Name: count, dtype: int64

In [45]:
df["Owner nam"].value_counts(dropna=False).head(30)

Owner nam
NaN             8426
Pw User         1618
Ali              610
Abdullah         256
Hamza            255
Ahmed            228
Malik            218
Usman            212
Khan             205
Ahmad            203
Hassan           199
Muhammad         195
Bilal            177
Imran            144
Abdul Rehman     127
Buyer            123
Salman           115
Zeeshan          110
Umer             107
Ahsan            104
Faisal            99
Saad              98
User              98
Umair             96
Muhammad Ali      96
Adnan             92
Fahad             89
Asif              88
Asad              88
Waqas             87
Name: count, dtype: int64

In [46]:
df[df["Ad Reference"].duplicated(keep=False)].sort_values("Ad Reference")

,nam,Price,Year,Millage,Fuel,Transmission,Province,Color,Assembly,Engine Capacity,Body Type,Ad Reference,Features,Owner nam,url
14336,Toyota Fortuner 2.7 VVTi 2016,PKR 89.5 lacs,2016,"124,448 km",Petrol,Automatic,Lahore,White,Local,2700 cc,SUV,10222148,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/toyota-fo...
20158,Toyota Fortuner 2.7 VVTi 2016,PKR 85 lacs,2016,"124,448 km",Petrol,Automatic,Lahore,White,Local,2700 cc,SUV,10222148,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/toyota-fo...
15258,Hyundai Sonata 2.0 2021,PKR 80.75 lacs,2021,"35,000 km",Petrol,Automatic,Islamabad,Diamond Metallic Black,Local,2000 cc,Sedan,10227340,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Arbaz Khan,https://www.pakwheels.com//used-cars/hyundai-s...
9441,Hyundai Sonata 2.0 2021,PKR 82 lacs,2021,"35,000 km",Petrol,Automatic,Islamabad,Diamond Metallic Black,Local,2000 cc,Sedan,10227340,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Arbaz Khan,https://www.pakwheels.com//used-cars/hyundai-s...
19401,Honda Civic VTi Oriel 1.8 i-VTEC 2012,PKR 25 lacs,2012,"169,939 km",Petrol,Manual,Karachi,Polished Metal Metallic,Local,1800 cc,Sedan,10242626,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/honda-civ...
7882,Honda Civic VTi Oriel 1.8 i-VTEC 2012,PKR 26.75 lacs,2012,"169,939 km",Petrol,Manual,Karachi,Polished Metal Metallic,Local,1800 cc,Sedan,10242626,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/honda-civ...
18503,Toyota Corolla Altis X Automatic 1.6 2022,PKR 56.7 lacs,2022,"30,000 km",Petrol,Automatic,Sindh,Super White,Local,1598 cc,Sedan,10263059,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Hashir Irfan,https://www.pakwheels.com//used-cars/toyota-co...
37167,Toyota Corolla Altis X Automatic 1.6 2022,PKR 56.5 lacs,2022,"30,000 km",Petrol,Automatic,Sindh,Super White,Local,1598 cc,Sedan,10263059,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Hashir Irfan,https://www.pakwheels.com//used-cars/toyota-co...
23370,Peugeot 2008 Allure 2022,PKR 52.5 lacs,2022,"121,135 km",Petrol,Automatic,Islamabad,Clear White,Imported,1200 cc,Crossover,10271701,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/peugeot-2...
36421,Peugeot 2008 Allure 2022,PKR 55 lacs,2022,"121,135 km",Petrol,Automatic,Islamabad,Clear White,Imported,1200 cc,Crossover,10271701,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",NaN,https://www.pakwheels.com//used-cars/peugeot-2...
1919,Toyota Prado TX Limited 2.7 2010,PKR 1.58 crore,2010,"104,000 km",Petrol,Automatic,Lahore,Super White,Imported,2700 cc,SUV,10276294,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Salman Saeed,https://www.pakwheels.com//used-cars/toyota-pr...
7914,Toyota Prado TX Limited 2.7 2010,PKR 1.58 crore,2010,"104,000 km",Petrol,Automatic,Lahore,White,Imported,2700 cc,SUV,10276294,"['ABS', 'AM/FM Radio', 'Air Bags', 'Air Condit...",Salman Saeed,https://www.pakwheels.com//used-cars/toyota-pr...
15743,Daihatsu Cuore CL Eco 2008,PKR 12.85 lacs,2008,"99,000 km",Petrol,Manual,Lahore,White,Local,800 cc,Hatchback,10303949,"['AM/FM Radio', 'Air Conditioning', 'Cassette ...",Abc,https://www.pakwheels.com//used-cars/daihatsu-...
9957,Daihatsu Cuore CX Eco 2008,PKR 12.99 lacs,2008,"99,000 km",Petrol,Manual,Lahore,White,Local,800 cc,Hatchback,10303949,"['AM/FM Radio', 'Air Conditioning']",Abc,https://www.pakwheels.com//used-cars/daihatsu-...
10187,Suzuki Alto VXR 2024,PKR 27.8 lacs,2024,"17,000 km",Petrol,Manual,Punjab,White,Local,660 cc,Hatchback,10307493,"['AM/FM Radio', 'Air Bags', 'Air Conditioning'...",Muhammad Saleem,https://www.pakwheels.com//used-cars/suzuki-al...
15922,Suzuki Alto VXR 2024,PKR 27.6 lacs,2024,"17,000 km",Petrol,Manual,Punjab,White,Local,660 cc,Hatchback,10307493,"['AM/FM Radio', 'Air Bags', 'Air Conditioning'...",Muhammad Saleem,https://www.pakwheels.com//used-cars/suzuki-al...

In [47]:
df["Ad Reference"].duplicated().sum()

np.int64(8)

In [48]:
df["url"].duplicated().sum()

np.int64(8)

In [49]:
df.groupby("Ad Reference")["url"].nunique().sort_values(ascending=False).head(10)

Ad Reference
1955064    1
2155899    1
2184125    1
2583078    1
2670518    1
3881942    1
4547497    1
4581844    1
4686342    1
4779761    1
Name: url, dtype: int64

In [50]:
df.loc[df["Fuel"] == "Electric", "Engine Capacity"].value_counts()

Engine Capacity
60.0 kWh     52
71.0 kWh     40
20.0 kWh     40
40.0 kWh     34
80.0 kWh     25
             ..
99.8 kWh      1
65.0 kWh      1
94.0 kWh      1
101.7 kWh     1
92.0 kWh      1
Name: count, Length: 110, dtype: int64

In [51]:
df.loc[df["Fuel"] == "Electric", "Engine Capacity"].value_counts()

Engine Capacity
60.0 kWh     52
71.0 kWh     40
20.0 kWh     40
40.0 kWh     34
80.0 kWh     25
             ..
99.8 kWh      1
65.0 kWh      1
94.0 kWh      1
101.7 kWh     1
92.0 kWh      1
Name: count, Length: 110, dtype: int64

In [52]:
df["Engine Capacity"].str.extract(r"(\d+\.?\d*)")

          0
0       660
1       658
2      1500
3      1600
4      1600
...     ...
61914  1000
61915   660
61916  1300
61917  1500
61918  1300

[61919 rows x 1 columns]

In [53]:
df.loc[
    (df["Fuel"] != "Electric") &
    (df["Engine Capacity"].str.contains("kWh", na=False)),
    ["nam", "Fuel", "Engine Capacity"]
]

Empty DataFrame
Columns: [nam, Fuel, Engine Capacity]
Index: []

In [54]:
df.loc[
    (df["Fuel"] == "Electric") &
    (df["Engine Capacity"].str.contains("cc", case=False, na=False)),
    ["nam", "Fuel", "Engine Capacity"]
]

Empty DataFrame
Columns: [nam, Fuel, Engine Capacity]
Index: []

In [55]:
pd.crosstab(df["Fuel"], df["Assembly"])

Assembly  Imported  Local
Fuel
CNG            164    487
Diesel        1051   1207
Electric       417    133
Hybrid        4170    705
LPG             42    112
Petrol       16985  36446

In [56]:
df["Province"].value_counts().tail(30)

Province
Ahmed Pur East           1
Chiniot                  1
Malakand Agency          1
Chitral                  1
Topi                     1
Sohawa district daska    1
Daska                    1
Abdul Hakeem             1
Kamoke                   1
Bhikky                   1
Laliah                   1
Kunri                    1
Sadiqabad                1
Rajanpur                 1
Dera Bugti               1
Hassan abdal             1
Dina                     1
Lala musa                1
Gwadar                   1
Kot Momin                1
Mian Channu              1
Charsadda                1
Umer Kot                 1
Panjan kisan             1
Kala bagh                1
Hazro                    1
Gambat                   1
Pindi gheb               1
Hasilpur                 1
Matli                    1
Name: count, dtype: int64

In [58]:
df.loc[
    df["nam"].str.contains("Automatic", case=False, na=False),
    "Transmission"
].value_counts()

Transmission
Automatic    2536
Manual         11
Name: count, dtype: int64

In [59]:
df.loc[
    df["nam"].str.contains("Automatic", case=False, na=False)
    & (df["Transmission"] == "Manual"),
    ["nam", "Year", "Transmission", "Price"]
]

,nam,Year,Transmission,Price
6596,Nissan Sunny Super Saloon Automatic 1.6 1990,1990,Manual,PKR 14 lacs
18301,Chevrolet Optra 1.6 Automatic 2005,2005,Manual,PKR 15 lacs
27077,Toyota Corolla GLi Automatic 1.3 VVTi 2015,2015,Manual,PKR 30 lacs
31701,Toyota Corolla GLi Automatic 1.3 VVTi 2018,2018,Manual,PKR 48 lacs
34733,Toyota Corolla Altis Automatic 1.8 2005,2005,Manual,PKR 22.65 lacs
35881,Toyota Corolla GLi Automatic 1.3 VVTi 2018,2018,Manual,PKR 43.5 lacs
43484,Toyota Hilux Revo G Automatic 2.8 2020,2020,Manual,PKR 92 lacs
47508,Toyota Corolla Altis Automatic 1.8 2005,2005,Manual,PKR 21 lacs
54424,Honda Civic VTi Automatic 1.6 2000,2000,Manual,PKR 13.95 lacs
56673,Toyota Corolla GLi Automatic 1.3 VVTi 2018,2018,Manual,PKR 32 lacs
61080,Suzuki Liana Eminent Automatic 1.3 2006,2006,Manual,PKR 15 lacs

In [60]:
df.loc[
    df["nam"].str.contains("Manual", case=False, na=False)
    & (df["Transmission"] == "Automatic"),
    ["nam", "Year", "Transmission", "Price"]
]

                             nam  Year Transmission          Price
29978  Suzuki Alto E Manual 2012  2012    Automatic  PKR 16.7 lacs

In [61]:
cc_values = pd.to_numeric(
    df.loc[
        df["Engine Capacity"].str.contains("cc", case=False, na=False),
        "Engine Capacity"
    ].str.replace("cc", "", case=False).str.strip(),
    errors="coerce"
)

cc_values.describe()

count    61369.000000
mean      1341.581043
std        726.080560
min        100.000000
25%        800.000000
50%       1300.000000
75%       1500.000000
max      15000.000000
Name: Engine Capacity, dtype: float64

In [62]:
df.loc[
    df["Engine Capacity"].str.contains("cc", case=False, na=False),
    ["nam", "Engine Capacity", "Body Type", "Fuel", "Price"]
].assign(
    engine_cc=lambda x: pd.to_numeric(
        x["Engine Capacity"]
        .str.replace("cc", "", case=False)
        .str.strip(),
        errors="coerce"
    )
).sort_values("engine_cc", ascending=False).head(20)

,nam,Engine Capacity,Body Type,Fuel,Price,engine_cc
44664,Toyota Prius 2006,15000 cc,NaN,Hybrid,PKR 32.5 lacs,15000
43038,Haval H6 2024,15000 cc,NaN,Hybrid,PKR 1.17 crore,15000
61101,Honda Civic 2003,15000 cc,NaN,Petrol,PKR 14 lacs,15000
50882,Honda Civic 1995,15000 cc,NaN,Petrol,PKR 8.65 lacs,15000
11875,Honda HR-V 2025,15000 cc,NaN,Petrol,PKR 75 lacs,15000
56278,Nissan AD Van 2006,15000 cc,NaN,Petrol,PKR 15 lacs,15000
33874,Honda City 2018,15000 cc,NaN,Petrol,PKR 36 lacs,15000
11198,Suzuki Ciaz 2016,14000 cc,NaN,Petrol,PKR 26.75 lacs,14000
27068,Honda Civic 1996,14000 cc,NaN,CNG,PKR 8.5 lacs,14000
51284,Suzuki Liana 2007,13002 cc,NaN,Petrol,PKR 11 lacs,13002
27253,Daihatsu Charade 1986,13000 cc,NaN,Petrol,PKR 11 lacs,13000
4600,Nissan Kicks 2020,13000 cc,NaN,Hybrid,PKR 79.75 lacs,13000
12349,Nissan Sunny 1993,13000 cc,NaN,Petrol,PKR 3.5 lacs,13000
48621,Suzuki FX 1988,12558 cc,NaN,Petrol,PKR 4.2 lacs,12558
21596,Toyota Hiace 1989,12345 cc,NaN,Diesel,PKR 16.9 lacs,12345
39062,Toyota Passo 2007,12000 cc,NaN,Petrol,PKR 22.5 lacs,12000
26907,Mitsubishi Pajero 1997,11000 cc,NaN,Petrol,PKR 15.5 lacs,11000
35574,Suzuki Spacia 1996,10000 cc,NaN,CNG,PKR 5.5 lacs,10000
40700,Hyundai Santro 2006,10000 cc,NaN,Petrol,PKR 12 lacs,10000
42837,Suzuki Khyber 1992,10000 cc,NaN,Petrol,PKR 4.5 lacs,10000

In [63]:
(cc_values > 7000).sum()

np.int64(29)

In [64]:
df.loc[
    df["Engine Capacity"].str.contains("cc", case=False, na=False)
    & (
        pd.to_numeric(
            df["Engine Capacity"]
            .str.replace("cc", "", case=False)
            .str.strip(),
            errors="coerce"
        ) < 500
    ),
    ["nam", "Engine Capacity", "Body Type", "Fuel", "Price"]
].sort_values("Engine Capacity")

,nam,Engine Capacity,Body Type,Fuel,Price
57134,Toyota Corolla 2016,100 cc,NaN,Petrol,PKR 38 lacs
44795,Daihatsu Mira 2015,100 cc,NaN,Petrol,PKR 23.5 lacs
44727,Honda City 2008,100 cc,NaN,Petrol,PKR 23 lacs
43589,Honda City 2002,100 cc,NaN,Petrol,PKR 12 lacs
49485,Suzuki Margalla 1995,100 cc,NaN,Petrol,PKR 5.8 lacs
42004,Suzuki Mehran 2004,100 cc,NaN,Petrol,PKR 6.9 lacs
40818,Toyota Corolla 2011,100 cc,NaN,Petrol,PKR 22.75 lacs
37079,Honda City 2005,100 cc,NaN,Petrol,PKR 17.6 lacs
36656,Nissan Sunny 1987,100 cc,NaN,Petrol,PKR 3.5 lacs
56993,Toyota Corolla 2016,100 cc,NaN,Petrol,PKR 34.5 lacs
33879,Honda Civic 2017,100 cc,NaN,Petrol,PKR 45 lacs
52267,Power Mini Bus 2013,100 cc,NaN,Petrol,PKR 10 lacs
32742,Suzuki Khyber 2000,100 cc,NaN,Petrol,PKR 7.8 lacs
48680,Honda Airwave 1995,100 cc,NaN,Petrol,PKR 13 lacs
52848,Toyota Vitz 2007,100 cc,NaN,CNG,PKR 20.5 lacs
28544,Suzuki Potohar 2006,100 cc,NaN,Petrol,PKR 15.5 lacs
28485,Toyota Corolla 2000,100 cc,NaN,Diesel,PKR 14 lacs
27150,Suzuki MR Wagon 2017,100 cc,NaN,Petrol,PKR 22.5 lacs
26815,Suzuki Alto 2021,100 cc,NaN,Petrol,PKR 32.5 lacs
26425,Toyota Hiace 2010,100 cc,NaN,Petrol,PKR 45 lacs
54329,Suzuki Alto 2006,100 cc,NaN,CNG,PKR 9 lacs
25516,Toyota Corolla 1996,100 cc,NaN,Petrol,PKR 20 lacs
25121,Honda City 2002,100 cc,NaN,Petrol,PKR 15 lacs
22427,Suzuki Bolan 2016,100 cc,NaN,Petrol,PKR 15.5 lacs
55934,Subaru Dias Wagon 2018,100 cc,NaN,Petrol,PKR 8.5 lacs
16067,Suzuki Mehran 1996,100 cc,NaN,Petrol,PKR 4.5 lacs
9277,Suzuki Mehran 2016,100 cc,NaN,Petrol,PKR 12.5 lacs
49193,Suzuki Cultus 2007,100 cc,NaN,Petrol,PKR 11.7 lacs
30157,Nissan Sentra 2005,123 cc,NaN,Petrol,PKR 13.75 lacs
7049,Toyota Hiace 1996,125 cc,NaN,LPG,PKR 24.5 lacs
33882,Changan Karvaan 2019,140 cc,NaN,Petrol,PKR 18 lacs
55057,Toyota Corolla 2010,160 cc,NaN,Petrol,PKR 25.5 lacs
26421,Toyota Noah 2001,200 cc,NaN,Petrol,PKR 16.5 lacs
42073,Toyota Vitz 2013,200 cc,NaN,Petrol,PKR 28.5 lacs
16611,Suzuki Mehran 1997,222 cc,NaN,Petrol,PKR 4 lacs
31657,Mercedes Benz E Class 1985,230 cc,NaN,Petrol,PKR 45 lacs
33011,Suzuki Bolan 1984,380 cc,NaN,Petrol,PKR 3.3 lacs

In [65]:
(cc_values < 500).sum()

np.int64(37)

In [66]:
mileage_values = pd.to_numeric(
    df["Millage"]
    .str.replace(",", "", regex=False)
    .str.replace("km", "", case=False)
    .str.strip(),
    errors="coerce"
)

mileage_values.describe()

count      61919.000000
mean       99841.268044
std        92636.581567
min            1.000000
25%        44000.000000
50%        87254.000000
75%       131000.000000
max      1000000.000000
Name: Millage, dtype: float64

In [67]:
df.assign(
    mileage_km=mileage_values
)[
    ["nam", "Millage", "Year", "Fuel", "Price", "mileage_km"]
].sort_values(
    "mileage_km", ascending=False
).head(20)

,nam,Millage,Year,Fuel,Price,mileage_km
37523,Suzuki Alto VX 2007,"1,000,000 km",2007,Petrol,PKR 8 lacs,1000000
45292,Toyota Land Cruiser 1974,"1,000,000 km",1974,Diesel,PKR 13 lacs,1000000
13064,Toyota Corolla GL 1996,"1,000,000 km",1996,Petrol,PKR 8.7 lacs,1000000
37440,Suzuki Ravi 2012,"1,000,000 km",2012,Petrol,PKR 9.2 lacs,1000000
44460,Suzuki Cultus EURO II 2012,"1,000,000 km",2012,Petrol,PKR 14 lacs,1000000
45325,Suzuki Mehran VXR Euro II 2016,"1,000,000 km",2016,Petrol,PKR 14.4 lacs,1000000
53576,Toyota Corolla 1973,"1,000,000 km",1973,CNG,PKR 4.5 lacs,1000000
53551,Suzuki Mehran VXR Euro II 2013,"1,000,000 km",2013,Petrol,PKR 10.5 lacs,1000000
61253,Suzuki Alto VXR 2008,"1,000,000 km",2008,Petrol,PKR 11.5 lacs,1000000
50920,Daihatsu Cuore CX Automatic 2007,"1,000,000 km",2007,Petrol,PKR 11.7 lacs,1000000
21554,Hyundai Shehzore Pickup H-100 2005,"1,000,000 km",2005,Diesel,PKR 32.3 lacs,1000000
29027,Suzuki Alto VXR 2009,"1,000,000 km",2009,CNG,PKR 11 lacs,1000000
13074,Suzuki Mehran VX 2006,"1,000,000 km",2006,Petrol,PKR 6.5 lacs,1000000
13034,Suzuki Cultus VXR 2005,"1,000,000 km",2005,Petrol,PKR 8.8 lacs,1000000
26484,Suzuki Mehran 1990,"1,000,000 km",1990,Petrol,PKR 5.5 lacs,1000000
56820,Suzuki Bolan Cargo Van Euro ll 2015,"1,000,000 km",2015,Petrol,PKR 9.7 lacs,1000000
35984,Suzuki Mehran VXR 2007,"1,000,000 km",2007,Petrol,PKR 6 lacs,1000000
49193,Suzuki Cultus 2007,"1,000,000 km",2007,Petrol,PKR 11.7 lacs,1000000
31581,Toyota Corolla XLi 2006,"1,000,000 km",2006,Petrol,PKR 20 lacs,1000000
27596,Suzuki Mehran VX 1991,"1,000,000 km",1991,Petrol,PKR 4.5 lacs,1000000

In [68]:
(mileage_values == 1_000_000).sum()

np.int64(59)

In [69]:
df.loc[
    mileage_values == 1,
    ["nam", "Year", "Millage", "Price", "Fuel", "Assembly"]
].sort_values("Year").head(30)

,nam,Year,Millage,Price,Fuel,Assembly
45416,Hyundai Excel 1963,1963,1 km,PKR 3.7 lacs,Petrol,Local
33033,Toyota Mark II 1974,1974,1 km,PKR 20 lacs,Petrol,Imported
53863,Toyota Corolla 1975,1975,1 km,PKR 13.1 lacs,Petrol,Imported
49553,Toyota Corolla 1977,1977,1 km,PKR 5.3 lacs,CNG,Local
52470,Jeep CJ 5 1981,1981,1 km,PKR 21 lacs,Diesel,Local
50116,Suzuki Ravi Standard 1982,1982,1 km,PKR 3.2 lacs,Petrol,Local
11928,Toyota Land Cruiser 1982,1982,1 km,PKR 18.5 lacs,Diesel,Imported
44827,Datsun 120 Y 1983,1983,1 km,PKR 9 lacs,Petrol,Imported
31218,Honda Accord 1984,1984,1 km,PKR 4.5 lacs,Petrol,Imported
60276,Nissan Sunny 1985,1985,1 km,PKR 6.8 lacs,Petrol,Imported
52340,Daihatsu Charade 1985,1985,1 km,PKR 4.9 lacs,Petrol,Imported
40183,Suzuki Swift 1985,1985,1 km,PKR 3.25 lacs,Petrol,Local
9125,Daihatsu Charade CX 1986,1986,1 km,PKR 5 lacs,Petrol,Imported
58801,Toyota Corolla 1986,1986,1 km,PKR 4.4 lacs,Petrol,Local
49699,Toyota Corolla GL Saloon 1986,1986,1 km,PKR 7 lacs,Petrol,Local
28961,Nissan Caravan 1986,1986,1 km,PKR 4 lacs,CNG,Imported
56787,Mitsubishi Pajero Exceed 2.5D 1986,1986,1 km,PKR 10.8 lacs,Diesel,Imported
56337,Toyota Corolla DX 1987,1987,1 km,PKR 7.8 lacs,Petrol,Imported
17987,Toyota Land Cruiser 1987,1987,1 km,PKR 25 lacs,Petrol,Imported
46239,Suzuki FX 1987,1987,1 km,PKR 3.2 lacs,Petrol,Imported
53071,Toyota 86 1988,1988,1 km,PKR 6 lacs,Diesel,Imported
21059,Toyota Crown 1988,1988,1 km,PKR 6.8 lacs,Petrol,Imported
25546,Toyota Corolla SE Limited 1988,1988,1 km,PKR 7.95 lacs,Petrol,Local
25184,Suzuki Ravi Deckless 1988,1988,1 km,PKR 2.95 lacs,Petrol,Local
43777,Mitsubishi Pajero Exceed 2.5D 1988,1988,1 km,PKR 13 lacs,Diesel,Imported
47697,Suzuki FX 1989,1989,1 km,PKR 2.2 lacs,Petrol,Local
32968,Suzuki Mehran VXR (CNG) 1989,1989,1 km,PKR 3.45 lacs,Petrol,Local
40977,Mitsubishi Pajero 1989,1989,1 km,PKR 19 lacs,Diesel,Imported
16851,Suzuki Mehran VX 1990,1990,1 km,PKR 3.3 lacs,Petrol,Local
57931,Suzuki Khyber GA 1990,1990,1 km,PKR 4.75 lacs,Petrol,Local

In [70]:
df.assign(
    mileage_km=mileage_values
).loc[
    (mileage_values > 1) & (mileage_values <= 100),
    ["nam", "Year", "Millage", "Price", "mileage_km"]
].sort_values("mileage_km").head(40)

,nam,Year,Millage,Price,mileage_km
34061,BAW Brumby EV 2025,2025,2 km,PKR 38 lacs,2
34131,Suzuki Alto VXL AGS Upgraded 2025,2025,2 km,PKR 33.5 lacs,2
18668,Haval Jolion HEV 2025,2025,2 km,PKR 96.2 lacs,2
3809,Haval H6 HEV 2025,2025,2 km,PKR 1.26 crore,2
1624,JAC X200 Base Grade 2000,2000,2 km,PKR 24 lacs,2
50435,Mitsubishi Pajero Exceed 2.5D 1988,1988,2 km,PKR 19.8 lacs,2
50302,Chevrolet Optra 2005,2005,2 km,PKR 15 lacs,2
30055,Honda Fit Shuttle Hybrid 1.3 2014,2014,2 km,PKR 36.4 lacs,2
58479,Suzuki Mehran VX 2009,2009,2 km,PKR 7.45 lacs,2
58090,Hyundai Tucson 2025,2025,2 km,PKR 1.29 crore,2
6335,Haval H6 1.5T 2025,2025,2 km,Call for price,2
15430,Haval Jolion 1.5T 2025,2025,2 km,PKR 82 lacs,2
22186,KIA Sorento 3.5 FWD 2025,2025,2 km,PKR 1.56 crore,2
22204,Haval H6 HEV 2025,2025,2 km,Call for price,2
22169,Suzuki Swift GLX CVT 2025,2025,2 km,PKR 50.8 lacs,2
18280,KIA Sportage L Alpha 2025,2025,2 km,Call for price,2
6533,Hyundai Shehzore Pickup H-100 2025,2025,2 km,PKR 44.21 lacs,2
6371,Suzuki Alto VXL AGS 2025,2025,2 km,PKR 33.26 lacs,2
5799,Hyundai Tucson Hybrid Signature 2025,2025,2 km,PKR 1.26 crore,2
8064,Changan Oshan X7 FutureSense 2025,2025,2 km,PKR 92.8 lacs,2
26613,ORA 03 400-Pro 2025,2025,2 km,PKR 80.5 lacs,2
42965,BAIC BJ40 Exclusive 2025,2025,2 km,Call for price,2
19961,Haval Jolion 1.5T 2025,2025,2 km,PKR 82 lacs,2
13732,Suzuki Mehran VX 1996,1996,2 km,PKR 3.75 lacs,2
46735,Haval H6 2.0T AWD 2025,2025,2 km,Call for price,2
13851,Honda City i-DSI 2004,2004,2 km,PKR 14.65 lacs,2
37435,Honda Civic 1995,1995,2 km,PKR 7 lacs,2
22109,Suzuki Alto VXR 2025,2025,2 km,PKR 31 lacs,2
51858,Suzuki Baleno JXR 2004,2004,2 km,PKR 9.49 lacs,2
57550,KIA EV5 EARTH 2025,2025,2 km,Call for price,2
27345,Haval H6 1.5T 2025,2025,2 km,PKR 94.23 lacs,2
6601,Suzuki Cultus VXL 2025,2025,2 km,PKR 43.59 lacs,2
7595,Changan Karvaan Plus 2025,2025,2 km,PKR 32.97 lacs,2
26471,Suzuki Alto E Manual 2009,2009,2 km,PKR 8.5 lacs,2
26804,Toyota Hilux Revo GR-S 2025,2025,2 km,Call for price,2
8179,Toyota Passo 2008,2008,2 km,PKR 21 lacs,2
12480,Suzuki Alto G 2007,2007,2 km,PKR 17.2 lacs,2
55315,Toyota Corolla GLi 1.3 VVTi 2016,2016,2 km,PKR 35.4 lacs,2
60742,Toyota Starlet 1978,1978,2 km,PKR 9 lacs,2
10404,Suzuki Every VXR 2025,2025,2 km,PKR 27.99 lacs,2

In [71]:
df.assign(
    mileage_km=mileage_values
).loc[
    mileage_values <= 100
].groupby("Year").size().sort_index()

Year
1963       1
1965       1
1974       2
1975       1
1977       1
1978       1
1980       2
1981       2
1982       2
1983       4
1984       3
1985       6
1986       9
1987       7
1988      14
1989       8
1990       6
1991      10
1992       8
1993       7
1994      10
1995      12
1996      15
1997      10
1998      14
1999      11
2000      11
2001       9
2002      14
2003      22
2004      28
2005      39
2006      41
2007      66
2008      34
2009      28
2010      22
2011      29
2012      23
2013      23
2014      20
2015      13
2016      23
2017      23
2018      25
2019      21
2020      21
2021      26
2022      28
2023      26
2024      35
2025    1006
dtype: int64

In [72]:
(mileage_values <= 100).sum()

np.int64(1823)

In [73]:
def price_to_pkr(price):
    price = str(price).lower().replace("pkr", "").strip()

    if price == "call for price":
        return None

    if "crore" in price:
        return float(price.replace("crore", "").strip()) * 10_000_000

    if "lacs" in price:
        return float(price.replace("lacs", "").strip()) * 100_000

    return None


price_values = df["Price"].apply(price_to_pkr)

price_values.describe()

count    6.106600e+04
mean     4.068249e+06
std      6.385513e+06
min      1.300000e+05
25%      1.470000e+06
50%      2.700000e+06
75%      4.450000e+06
max      2.500000e+08
Name: Price, dtype: float64

In [74]:
df.assign(
    price_pkr=price_values
)[
    ["nam", "Price", "Year", "Fuel", "Transmission", "Engine Capacity", "price_pkr"]
].sort_values(
    "price_pkr", ascending=False
).head(20)

,nam,Price,Year,Fuel,Transmission,Engine Capacity,price_pkr
17806,Mercedes Benz S Class S 63 E Performance AMG 2023,PKR 25 crore,2023,Hybrid,Automatic,4000 cc,250000000.0
27064,Lamborghini Urus 2020,PKR 20 crore,2020,Petrol,Automatic,4000 cc,200000000.0
16510,Lamborghini Urus Performante 2020,PKR 19.65 crore,2020,Petrol,Automatic,4000 cc,196500000.0
23261,Mercedes Benz G Class G 63 AMG 2020,PKR 16.75 crore,2020,Petrol,Automatic,4000 cc,167500000.0
24871,Mercedes Benz G Class G 63 AMG 2020,PKR 15.75 crore,2020,Petrol,Automatic,4000 cc,157500000.0
88,Mercedes Benz G Class G 63 AMG 2020,PKR 15.5 crore,2020,Petrol,Automatic,4000 cc,155000000.0
22040,Mercedes Benz G Class G 63 AMG 2020,PKR 15.5 crore,2020,Petrol,Automatic,4000 cc,155000000.0
4763,Lexus LX Series LX 600 Ultra Luxury 2023,PKR 15 crore,2023,Petrol,Automatic,3500 cc,150000000.0
17640,Mercedes Benz S Class S 500 4MATIC 2021,PKR 13.5 crore,2021,Petrol,Automatic,3000 cc,135000000.0
28557,Toyota Land Cruiser ZX Gasoline 3.5L 2025,PKR 13 crore,2025,Petrol,Automatic,3500 cc,130000000.0
17751,Lexus GX GX 550 Version L 2025,PKR 12.95 crore,2025,Petrol,Automatic,3400 cc,129500000.0
19897,Lexus GX GX 550 Version L 2025,PKR 12.95 crore,2025,Petrol,Automatic,3400 cc,129500000.0
20835,Lexus LX Series LX 600 Ultra Luxury 2025,PKR 12.75 crore,2025,Petrol,Automatic,3500 cc,127500000.0
57312,Lexus LX Series 2023,PKR 12.65 crore,2023,Petrol,Automatic,3500 cc,126500000.0
10951,Mercedes Benz G Class G 580 EQ 2025,PKR 12.25 crore,2025,Electric,Automatic,4000.0 kWh,122500000.0
12005,Mercedes Benz G Class G 580 EQ 2025,PKR 12.25 crore,2025,Electric,Automatic,116.0 kWh,122500000.0
3667,Mercedes Benz G Class G 63 AMG 2016,PKR 12 crore,2016,Petrol,Automatic,5500 cc,120000000.0
21633,Mercedes Benz S Class 2021,PKR 12 crore,2021,Petrol,Automatic,3000 cc,120000000.0
24168,Toyota Land Cruiser ZX Gasoline 3.5L 2024,PKR 12 crore,2024,Petrol,Automatic,3500 cc,120000000.0
17790,Lexus LX Series LX 600 Ultra Luxury 2023,PKR 12 crore,2023,Petrol,Automatic,3500 cc,120000000.0

In [75]:
battery_kwh = pd.to_numeric(
    df.loc[
        df["Fuel"] == "Electric",
        "Engine Capacity"
    ].str.replace("kWh", "", case=False).str.strip(),
    errors="coerce"
)

battery_kwh.sort_values(ascending=False).head(20)

1682     4992.0
17814    4992.0
18519    4992.0
18889    4992.0
24514    4000.0
10951    4000.0
33761    3000.0
16770    2127.0
51731    1500.0
48800    1200.0
40189    1070.0
26437    1070.0
21254    1050.0
33864    1050.0
7859     1020.0
5017     1000.0
24472     934.0
24165     934.0
19132     934.0
28305     934.0
Name: Engine Capacity, dtype: float64

In [76]:
ev_audit = df.loc[
    df["Fuel"] == "Electric",
    ["nam", "Engine Capacity", "Year", "Price"]
].copy()

ev_audit["battery_kwh"] = battery_kwh

ev_audit.loc[
    ev_audit["battery_kwh"] > 200
].sort_values(
    "battery_kwh", ascending=False
)

,nam,Engine Capacity,Year,Price,battery_kwh
1682,BYD Atto 3 Advance 2025,4992.0 kWh,2025,PKR 94 lacs,4992.0
17814,BYD Atto 3 Advance 2025,4992.0 kWh,2025,PKR 94.5 lacs,4992.0
18889,BYD Atto 3 Advance 2025,4992.0 kWh,2025,PKR 94.25 lacs,4992.0
18519,BYD Atto 3 Advance 2025,4992.0 kWh,2025,PKR 94.5 lacs,4992.0
10951,Mercedes Benz G Class G 580 EQ 2025,4000.0 kWh,2025,PKR 12.25 crore,4000.0
24514,Mercedes Benz G Class G 580 EQ 2025,4000.0 kWh,2025,PKR 11.45 crore,4000.0
33761,Honri Ve 2019,3000.0 kWh,2019,PKR 12 lacs,3000.0
16770,GMC Hummer EV Pickup Edition 1 2022,2127.0 kWh,2022,PKR 5.99 crore,2127.0
51731,MG 5 EV 2025,1500.0 kWh,2025,PKR 98 lacs,1500.0
48800,Nissan Note MEDALIST 2017,1200.0 kWh,2017,PKR 39.8 lacs,1200.0
40189,Mercedes Benz EQS 450 4MATIC 2022,1070.0 kWh,2022,Call for price,1070.0
26437,Mercedes Benz EQS 2022,1070.0 kWh,2022,Call for price,1070.0
21254,BMW 7 Series i7 xDrive60 Excellence 2022,1050.0 kWh,2022,Call for price,1050.0
33864,BMW 7 Series i7 xDrive60 Excellence 2022,1050.0 kWh,2022,PKR 6.9 crore,1050.0
7859,BMW 7 Series i7 xDrive60 M Pro Package 2023,1020.0 kWh,2023,PKR 6.85 crore,1020.0
5017,Nissan Leaf EV 2021,1000.0 kWh,2021,PKR 70 lacs,1000.0
19132,Audi e-tron GT Standard 2022,934.0 kWh,2022,PKR 3.45 crore,934.0
24472,Audi e-tron GT RS 2021,934.0 kWh,2021,Call for price,934.0
28305,Porsche Taycan 2021,934.0 kWh,2021,PKR 3.9 crore,934.0
24165,Audi e-tron GT Standard 2023,934.0 kWh,2023,Call for price,934.0
20250,Tesla Model S 85D 2021,850.0 kWh,2021,PKR 1.6 crore,850.0
25855,Mercedes Benz EQC 400 4MATIC 2020,800.0 kWh,2020,PKR 1.75 crore,800.0
44671,Mercedes Benz EQC 400 4MATIC 2020,800.0 kWh,2020,PKR 2.25 crore,800.0
21974,Mercedes Benz EQC 400 4MATIC 2020,800.0 kWh,2020,PKR 1.95 crore,800.0
15553,Mercedes Benz EQC 400 4MATIC 2020,800.0 kWh,2020,PKR 2.05 crore,800.0
9474,Mercedes Benz EQC 400 4MATIC 2020,800.0 kWh,2020,PKR 1.75 crore,800.0
25220,Tesla Model 3 Long Range 2021,750.0 kWh,2021,PKR 1.75 crore,750.0
20285,Porsche Taycan Base Model 2021,710.0 kWh,2021,PKR 3.65 crore,710.0
23275,Porsche Taycan 4S 2021,710.0 kWh,2021,Call for price,710.0
25316,BMW iX xDrive40 2022,710.0 kWh,2022,PKR 3.25 crore,710.0
8104,Porsche Taycan Base Model 2022,710.0 kWh,2022,PKR 3.85 crore,710.0
21306,Porsche Taycan 4S 2020,710.0 kWh,2020,PKR 4.15 crore,710.0
15669,Deepal L07 EV 2025,668.0 kWh,2025,PKR 1.4 crore,668.0
21938,Nissan Ariya B6 Limited 2023,660.0 kWh,2023,PKR 1.5 crore,660.0
10435,MG 4 Essence 2025,640.0 kWh,2025,PKR 98.28 lacs,640.0
24535,MG 4 Essence 2024,640.0 kWh,2024,PKR 1.18 crore,640.0
23366,Nissan Leaf e+ 2020,620.0 kWh,2020,Call for price,620.0
9873,Nissan Leaf e+ 2021,620.0 kWh,2021,PKR 90 lacs,620.0
5481,Audi e-tron 50 quattro 230 kW 2022,600.0 kWh,2022,Call for price,600.0
27690,Audi e-tron 50 quattro 230 kW 2021,600.0 kWh,2021,PKR 1.85 crore,600.0
26848,Audi e-tron 50 quattro 230 kW 2021,600.0 kWh,2021,Call for price,600.0
18726,Lexus UX 300e 2021,550.0 kWh,2021,PKR 1.4 crore,550.0
17638,Lexus UX 300e 2021,550.0 kWh,2021,PKR 1.35 crore,550.0
23304,Lexus UX 300e 2021,550.0 kWh,2021,PKR 1.2 crore,550.0
60115,Lexus UX 300e 2021,550.0 kWh,2021,PKR 1.47 crore,550.0
33363,Mercedes Benz EQA 2021,500.0 kWh,2021,PKR 2.3 crore,500.0
9251,Audi e-tron 2021,500.0 kWh,2021,PKR 2.15 crore,500.0
26613,ORA 03 400-Pro 2025,480.0 kWh,2025,PKR 80.5 lacs,480.0
14731,ORA 03 400-Pro 2025,480.0 kWh,2025,PKR 90 lacs,480.0
18747,ORA 03 400-Pro 2025,480.0 kWh,2025,PKR 80.5 lacs,480.0
17745,Nissan Leaf EV 2021,400.0 kWh,2021,PKR 68 lacs,400.0
17129,Nissan Leaf EV 2022,400.0 kWh,2022,PKR 84.99 lacs,400.0
22387,Nissan Leaf EV 2021,400.0 kWh,2021,PKR 72 lacs,400.0
34731,Nissan Leaf 2022,300.0 kWh,2022,PKR 69 lacs,300.0
637,Audi e-tron 50 quattro 230 kW 2021,300.0 kWh,2021,PKR 1.9 crore,300.0
53712,MG ZS EV Luxury 2021,251.0 kWh,2021,PKR 65 lacs,251.0
24608,Audi e-tron 50 quattro Sportback 230kW 2021,230.0 kWh,2021,PKR 2.3 crore,230.0
8773,Audi e-tron 50 quattro 230 kW 2021,230.0 kWh,2021,PKR 1.9 crore,230.0
6981,GMC Hummer EV Pickup Edition 1 2022,212.0 kWh,2022,PKR 7.5 crore,212.0
22722,GMC Hummer EV Pickup Edition 1 2022,212.0 kWh,2022,PKR 3.5 crore,212.0

In [77]:
pd.cut(
    battery_kwh,
    bins=[0, 50, 100, 150, 200, 500, 1000, float("inf")],
    right=True
).value_counts().sort_index()

Engine Capacity
(0.0, 50.0]        145
(50.0, 100.0]      303
(100.0, 150.0]      40
(150.0, 200.0]       2
(200.0, 500.0]      15
(500.0, 1000.0]     30
(1000.0, inf]       15
Name: count, dtype: int64

In [78]:
df.assign(
    price_pkr=price_values
)[
    ["nam", "Price", "Year", "Millage", "Fuel", "Engine Capacity", "price_pkr"]
].sort_values(
    "price_pkr", ascending=True
).head(20)

,nam,Price,Year,Millage,Fuel,Engine Capacity,price_pkr
25861,Suzuki FX GA 1988,PKR 1.3 lacs,1988,"180,000 km",Petrol,800 cc,130000.0
60212,Suzuki FX GA 1987,PKR 1.4 lacs,1987,"80,000 km",Petrol,800 cc,140000.0
32220,Suzuki FX GA 1987,PKR 1.4 lacs,1987,"1,000 km",Petrol,800 cc,140000.0
57444,Suzuki FX GA 1988,PKR 1.45 lacs,1988,"200,000 km",Petrol,800 cc,145000.0
47743,Daihatsu Charade GT-ti 1993,PKR 1.6 lacs,1993,"89,000 km",Petrol,1000 cc,160000.0
40806,Suzuki FX GA 1987,PKR 1.6 lacs,1987,"700,000 km",Petrol,800 cc,160000.0
34352,Suzuki FX GA 1986,PKR 1.6 lacs,1986,"100,000 km",Petrol,800 cc,160000.0
36788,Suzuki FX GA 1984,PKR 1.6 lacs,1984,"2,000 km",Petrol,800 cc,160000.0
25069,Suzuki FX GA 1986,PKR 1.6 lacs,1986,"100,000 km",Petrol,800 cc,160000.0
35271,Suzuki FX GA 1985,PKR 1.6 lacs,1985,"252,525 km",Petrol,800 cc,160000.0
49121,Suzuki FX GA 1986,PKR 1.65 lacs,1986,"100,000 km",Petrol,800 cc,165000.0
58901,Daihatsu Charade 1986,PKR 1.65 lacs,1986,"108,000 km",Petrol,1000 cc,165000.0
43085,Suzuki FX GA 1988,PKR 1.7 lacs,1988,100 km,Petrol,800 cc,170000.0
56471,Suzuki Khyber GA 1990,PKR 1.7 lacs,1990,"100,000 km",Petrol,1000 cc,170000.0
20115,Daihatsu Charade CL 1986,PKR 1.7 lacs,1986,"100,000 km",Diesel,1000 cc,170000.0
45886,Suzuki FX GA 1986,PKR 1.7 lacs,1986,"23,000 km",Petrol,800 cc,170000.0
53109,Suzuki FX GA 1987,PKR 1.7 lacs,1987,"100,000 km",Petrol,800 cc,170000.0
36423,Suzuki FX GA 1987,PKR 1.7 lacs,1987,"120,000 km",Petrol,800 cc,170000.0
39808,Daihatsu Charade CL 1984,PKR 1.8 lacs,1984,"999,999 km",Petrol,1000 cc,180000.0
39889,Suzuki FX GA 1985,PKR 1.8 lacs,1985,"10,000 km",Petrol,800 cc,180000.0

In [79]:
price_values.skew()

np.float64(9.65647331574623)

In [80]:
price_values.quantile([
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
    0.995,
    0.999
])

0.500     2700000.0
0.750     4450000.0
0.900     7200000.0
0.950    10900000.0
0.990    30535000.0
0.995    41000000.0
0.999    73500000.0
Name: Price, dtype: float64

In [81]:
df.loc[
    price_values.isna(),
    "Price"
].value_counts()

Price
Call for price    853
Name: count, dtype: int64

In [82]:
df.loc[
    df["Body Type"].isna(),
    "nam"
].value_counts().head(30)

nam
Suzuki Wagon R 2022            35
Toyota Corolla 1982            32
Suzuki Liana 2006              28
Toyota Corolla 1988            28
Suzuki Alto 2007               27
Daihatsu Cuore 2007            27
Nissan AD Van 2006             26
Suzuki Alto 2021               25
Daihatsu Mira 2022             23
Nissan Sunny 1987              23
Honda Civic 2005               23
Toyota Corolla 1998            21
Suzuki Alto 2022               21
Suzuki Cultus 2007             21
Suzuki Alto 2023               20
Suzuki Cultus 2006             20
Daihatsu Cuore 2008            19
Toyota Corolla 2006            19
Toyota Corolla 2005            19
Toyota Yaris Hatchback 2022    19
Honda Civic 1988               19
Daihatsu Charade 1986          19
Suzuki Khyber 2000             19
Suzuki Mehran 2007             19
Toyota Corolla 1986            19
Daihatsu Mira 2012             18
Suzuki Bolan 2015              18
Nissan Clipper 2019            18
Suzuki Alto 2008               18
Suzuki Cultus 2011             17
Name: count, dtype: int64

In [83]:
df.loc[
    df["nam"] == "Suzuki Wagon R 2022",
    "Body Type"
].value_counts(dropna=False)

Body Type
NaN    35
Name: count, dtype: int64